id: I31B4C224
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 11:08:47.677458+00:00
last_modified: 2022-12-14 11:08:47.677463+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-072-012
  eft-text-version: 1.1.10 2020
  title: Toh_312-Entering_the_City_of_Vaisali-v2
bases:
  CC73:
    source_metadata: null
    order: 1
    base_file: CC73.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
